version: '3.8'

services:
  graduation:
    image: myusername/graduation:latest  
    ports:
      - "8088:8088"
    depends_on:
      - exchanger

  exchanger:
    image: myusername/exchanger:latest  
    ports:
      - "8089:8089"
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tatsh
      POSTGRES_DB: exchanger
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: